#-------------------------------
# General Site Settings
# designication
title: novus
email: novus@gmail.com
description: Custom made t-shirts


# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about'}
- {name: Shirts, url: '#shirts'}
- {name: Prices, url: '#prices'}
- {name: Contact, url: '#contact'}


# About Section
founderPics:
- {name: Noah, pos: 'Founder', pic: 'founder-habe.jpg'}
- {name: Liam, pos: 'Founder', pic: 'founder-habe.jpg'}
- {name: Ethan, pos: 'Founder', pic: 'founder-habe.jpg'}

# Shirts
shirts:
- {name: 'Black Forest', pic: 'shirt-1.jpg', price: '20€'}
- {name: 'White Forest', pic: 'shirt-1.jpg', price: '30€'}
- {name: 'Black Mountain', pic: 'shirt-1.jpg', price: '25$'}
- {name: 'White Mountain', pic: 'shirt-1.jpg', price: '10€'}
- {name: 'Gray Forest', pic: 'shirt-1.jpg', price: '5£'}
- {name: 'Gray Mountain', pic: 'shirt-1.jpg', price: '15£'}

# Additional services
additionalprices:
- {name: 'Shipping', price: '5€'}
- {name: 'Custom print', price: '10€'}
#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.


skills:
- {name: Communication, value: '7'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '8'}
- {name: UX Design, value: '4'}
- {name: Programming, value: '8'}

# -------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}


# ------------------------------
# Skills Section
proskills:
- {name: C++,   lvl: Beginner,  folder: 'skill-1', file: 'logo.jpg'}
- {name: Java,  lvl: Advanced,  folder: 'skill-2', file: 'logo.jpg'}
- {name: Html,  lvl: Advanced,  folder: 'skill-3', file: 'logo.jpg'}
- {name: JavaScript, lvl: Advanced,    folder: 'skill-4', file: 'logo.jpg'}
- {name: Progress OE, lvl: Expert,   folder: 'skill-5', file: 'logo.jpg'}
- {name: Css/Sass, lvl: Advanced,     folder: 'skill-6', file: 'logo.jpg'}
- {name: Python, lvl: Advance,       folder: 'skill-7', file: 'logo.jpg'}
- {name: Jekyll, lvl: Advance,          folder: 'skill-8', file: 'logo.jpg'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/designicated'}
- {icon: 'youtube', link: 'https://www.youtube.com/designicated'}
- {icon: 'facebook', link: 'http://www.facebook.com/designicated'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
